CREATE TABLE logs (
id INT AUTO_INCREMENT PRIMARY KEY,
id_usuario INT NOT NULL,
tipo VARCHAR(20) NOT NULL,
acao VARCHAR(50) NOT NULL,
arquivos VARCHAR(255),
descricao TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_logs_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);