CREATE TABLE produtos (
id INT AUTO_INCREMENT PRIMARY KEY,
id_categoria INT NOT NULL,
descricao VARCHAR(100) NOT NULL,
valor DOUBLE NOT NULL,
estoque INT NOT NULL DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP NULL DEFAULT NULL,
CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);