CREATE TABLE pedido (
id INT AUTO_INCREMENT PRIMARY KEY,
id_usuario INT NOT NULL,
mesa VARCHAR(20),
data DATE NOT NULL,
observacao LONGTEXT,
desconto DOUBLE DEFAULT 0,
ativo TINYINT(1) DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP NULL DEFAULT NULL,
CONSTRAINT fk_pedido_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);